#Horizontal Pod Autoscaling is used to create new pods based on the cpu utilization of each node
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment #your backend type
    name: backend #your deployment name
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization #if averageUtilization of server shoud less than 50 or else it will create new pod
        averageUtilization: 70